#!/usr/bin/env nu

# Rewrite the README section that lists the collection.
#
# Reads `clients.yaml` and scans `clients/` to classify each entry:
#   - active    — listed in clients.yaml AND a .nu file exists on disk
#   - pending   — listed in clients.yaml but no .nu file (generation pending or failed)
#   - dismissed — .nu file on disk but no longer in clients.yaml (upstream dropped)
#
# Everything in the README before the MARKER is preserved; the section after
# is replaced with the freshly-rendered tables.

const MARKER = "---\n\n## The collection\n"

def main [
    --config: path = "clients.yaml"
    --out-dir: path = "clients"
    --readme: path = "README.md"
] {
    let clients = (open $config | get -o clients | default [])
    let yaml_names = ($clients | get -o name | default [])
    let disk_names = (
        glob ($out_dir | path join "*.nu")
        | each {|p| $p | path basename | str replace --regex '\.nu$' '' }
    )

    let active = ($clients | where {|c| $c.name in $disk_names })
    let pending = ($clients | where {|c| not ($c.name in $disk_names) })
    let dismissed = ($disk_names | where {|n| not ($n in $yaml_names) })

    let body = (
        $"This collection contains ($active | length) active client\(s\).\n\n"
        + (render "Active" ($active | each {|c| { Client: $"[($c.name)]\(($out_dir)/($c.name).nu\)", Source: $"<($c.source)>" }}))
        + (if ($pending | is-empty) { "" } else { "\n\n" + (render "Pending" ($pending | each {|c| { Client: $c.name, Source: $"<($c.source)>" }})) })
        + (if ($dismissed | is-empty) { "" } else { "\n\n" + (render "Dismissed (no longer in clients.yaml; file kept on disk)" ($dismissed | each {|n| { Client: $"[($n)]\(($out_dir)/($n).nu\)" }})) })
    )

    let section = $"($MARKER)\n_Auto-generated by `scripts/template.nu`. Do not edit by hand._\n\n($body)\n"
    let existing = if ($readme | path exists) { open --raw $readme } else { "" }
    let prefix = if ($existing | str contains $MARKER) {
        ($existing | split row $MARKER | first | str trim --right) + "\n\n"
    } else {
        ($existing | str trim --right) + "\n\n"
    }
    $prefix + $section | save -f $readme
    print $"Wrote ($readme): ($active | length) active, ($pending | length) pending, ($dismissed | length) dismissed."
}

def render [title: string, rows: list]: nothing -> string {
    if ($rows | is-empty) {
        $"### ($title)\n\n_none_"
    } else {
        $"### ($title)\n\n" + ($rows | to md --pretty)
    }
}
