#!/usr/bin/env nu

# Render the full collection listing to CLIENTS.md and refresh the stats block in README.md.
#
# Reads `clients.yaml` and scans `clients/` to classify each entry:
#   - active    — listed in clients.yaml AND a .nu file exists on disk
#   - pending   — listed in clients.yaml but no .nu file (generation pending or failed)
#   - dismissed — .nu file on disk but no longer in clients.yaml (upstream dropped)
#
# CLIENTS.md is overwritten in full each run. README.md is updated in place
# between `<!-- STATS:START -->` / `<!-- STATS:END -->` markers; if the markers
# are absent the README is left untouched.
#
# `to md` (not `--pretty`) is used so the column-alignment padding doesn't
# inflate the file past GitHub's 512 KB markdown render limit.

def main [
    --config: path = "clients.yaml"
    --out-dir: path = "clients"
    --out: path = "CLIENTS.md"
    --readme: path = "README.md"
] {
    let clients = (open $config | get -o clients | default [])
    let yaml_names = ($clients | get -o name | default [])
    let disk_names = (
        glob ($out_dir | path join "*.nu")
        | each {|p| $p | path basename | str replace --regex '\.nu$' '' }
    )

    let active = ($clients | where {|c| $c.name in $disk_names })
    let pending = ($clients | where {|c| not ($c.name in $disk_names) })
    let dismissed = ($disk_names | where {|n| not ($n in $yaml_names) })

    let body = (
        $"($active | length) active client\(s\).\n\n"
        + (render "Active" ($active | each {|c| { Client: $"[($c.name)]\(($out_dir)/($c.name).nu\)", Source: $"<($c.source)>" }}))
        + (if ($pending | is-empty) { "" } else { "\n\n" + (render "Pending" ($pending | each {|c| { Client: $c.name, Source: $"<($c.source)>" }})) })
        + (if ($dismissed | is-empty) { "" } else { "\n\n" + (render "Dismissed (no longer in clients.yaml; file kept on disk)" ($dismissed | each {|n| { Client: $"[($n)]\(($out_dir)/($n).nu\)" }})) })
    )

    let content = $"# Clients\n\n_Auto-generated by `scripts/template.nu`. Do not edit by hand._\n\n($body)\n"
    $content | save -f $out
    print $"Wrote ($out): ($active | length) active, ($pending | length) pending, ($dismissed | length) dismissed."

    update_readme_stats $readme $out_dir $active
}

# Format an integer with thousands separators: 84312 -> "84,312".
def with_commas [n: int]: nothing -> string {
    let digits = ($n | into string | split chars | reverse)
    $digits
    | enumerate
    | each {|e|
        if ($e.index > 0) and (($e.index mod 3) == 0) { ["," $e.item] } else { [$e.item] }
    }
    | flatten
    | reverse
    | str join
}

# Compact a line count: 3402891 -> "3.4M", 84312 -> "84.3K".
def humanize_count [n: int]: nothing -> string {
    if $n >= 1_000_000 {
        $"(($n / 1_000_000) | math round --precision 1)M"
    } else if $n >= 1_000 {
        $"(($n / 1_000) | math round --precision 1)K"
    } else {
        $n | into string
    }
}

def update_readme_stats [readme_path: path, out_dir: path, active: list]: nothing -> nothing {
    if not ($readme_path | path exists) {
        print $"Skipped stats update: ($readme_path) not found."
        return
    }

    let readme = (open --raw $readme_path)
    if not ($readme | str contains "<!-- STATS:START -->") {
        print $"Skipped stats update: no <!-- STATS:START --> marker in ($readme_path)."
        return
    }

    # Scan every active client file. Real API operations are exported with a
    # quoted command name (`export def "thing get" [...]`); the bare
    # `export def commands` metadata helper is intentionally excluded.
    let per = (
        $active
        | each {|c|
            let lines = (open --raw ($out_dir | path join $"($c.name).nu") | lines)
            {
                ops: ($lines | where {|l| $l | str starts-with 'export def "' } | length),
                loc: ($lines | length),
            }
        }
    )
    let total_ops = ($per | get ops | math sum)
    let total_loc = ($per | get loc | math sum)

    let block = $"**(with_commas ($active | length))** clients · **(with_commas $total_ops)** operations · **(humanize_count $total_loc)** lines of Nu"

    let updated = (
        $readme
        | str replace --regex '(?s)<!-- STATS:START -->.*?<!-- STATS:END -->' $"<!-- STATS:START -->\n($block)\n<!-- STATS:END -->"
    )
    $updated | save -f $readme_path
    print $"Updated stats in ($readme_path)."
}

def render [title: string, rows: list]: nothing -> string {
    if ($rows | is-empty) {
        $"## ($title)\n\n_none_"
    } else {
        let count = ($rows | length)
        let table = ($rows | to md)
        [
            $"## ($title)"
            ""
            "<details>"
            $"<summary>($count) clients</summary>"
            ""
            $table
            ""
            "</details>"
        ] | str join "\n"
    }
}
