#!/usr/bin/env nu

# Render the full collection listing to CLIENTS.md.
#
# Reads `clients.yaml` and scans `clients/` to classify each entry:
#   - active    — listed in clients.yaml AND a .nu file exists on disk
#   - pending   — listed in clients.yaml but no .nu file (generation pending or failed)
#   - dismissed — .nu file on disk but no longer in clients.yaml (upstream dropped)
#
# The output is overwritten in full each run — no marker injection. The README
# carries a static link to CLIENTS.md and is not touched by this script.
#
# `to md` (not `--pretty`) is used so the column-alignment padding doesn't
# inflate the file past GitHub's 512 KB markdown render limit.

def main [
    --config: path = "clients.yaml"
    --out-dir: path = "clients"
    --out: path = "CLIENTS.md"
] {
    let clients = (open $config | get -o clients | default [])
    let yaml_names = ($clients | get -o name | default [])
    let disk_names = (
        glob ($out_dir | path join "*.nu")
        | each {|p| $p | path basename | str replace --regex '\.nu$' '' }
    )

    let active = ($clients | where {|c| $c.name in $disk_names })
    let pending = ($clients | where {|c| not ($c.name in $disk_names) })
    let dismissed = ($disk_names | where {|n| not ($n in $yaml_names) })

    let body = (
        $"($active | length) active client\(s\).\n\n"
        + (render "Active" ($active | each {|c| { Client: $"[($c.name)]\(($out_dir)/($c.name).nu\)", Source: $"<($c.source)>" }}))
        + (if ($pending | is-empty) { "" } else { "\n\n" + (render "Pending" ($pending | each {|c| { Client: $c.name, Source: $"<($c.source)>" }})) })
        + (if ($dismissed | is-empty) { "" } else { "\n\n" + (render "Dismissed (no longer in clients.yaml; file kept on disk)" ($dismissed | each {|n| { Client: $"[($n)]\(($out_dir)/($n).nu\)" }})) })
    )

    let content = $"# Clients\n\n_Auto-generated by `scripts/template.nu`. Do not edit by hand._\n\n($body)\n"
    $content | save -f $out
    print $"Wrote ($out): ($active | length) active, ($pending | length) pending, ($dismissed | length) dismissed."
}

def render [title: string, rows: list]: nothing -> string {
    if ($rows | is-empty) {
        $"## ($title)\n\n_none_"
    } else {
        $"## ($title)\n\n" + ($rows | to md)
    }
}
